services:
  nodebb:
    build: .
    # image: ghcr.io/nodebb/nodebb:latest
    restart: unless-stopped
    ports:
      - '4567:4567' 
    depends_on:
      - redis
    volumes:
      - nodebb-build:/usr/src/app/build
      - nodebb-uploads:/usr/src/app/public/uploads
      - nodebb-config:/opt/config
      - ./install/docker/setup.json:/usr/src/app/setup.json

  redis:
    image: redis:8.4.0-alpine
    restart: unless-stopped
    environment:
      - SKIP_FIX_PERMS=1
    command: ['redis-server', '--appendonly', 'yes', '--loglevel', 'warning']
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  nodebb-build:
  nodebb-uploads:
  nodebb-config: