name: Retire.js Vulnerability Scan

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  security-audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      working-directory: ${{ github.workspace }}

    - name: Run Retire.js Scan
      run: npx retire --severity high
      working-directory: ${{ github.workspace }}